### ISSUE TITLE
Time isn't displayed correctly

### ISSUE THREAD

**Issue by akshatdevp** [akshatdevp/CodingContestTracker#3]
Some sites have UTC time, while some have remaining hours. Fix without breaking the heroku app.(can't use the built-in function, doesn't work on heroku.)

**Comment by DanB288** [comment]
Hi Akshat , I would like to work on this issue.

**Comment by akshatdevp** [comment]
Please go ahead!

**Comment by DanB288** [comment]
Do you want all of them to be in remaining hours?
Or only the ones which are less than 48 hrs?

**Comment by akshatdevp** [comment]
All of them
